---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
workflows:
  archive_and_export_app:
    summary: Run your Xcode tests and create an IPA file to install your app on a
      device or share it with your team.
    description: The workflow will first clone your Git repository, cache and install
      your project's dependencies if any, run your Xcode tests, export an IPA file
      from the project and save it.
    steps:
    - git-clone@8: {}
    - xcode-test@5:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - test_repetition_mode: retry_on_failure
        - cache_level: none
    - xcode-archive@5:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - distribution_method: "$BITRISE_DISTRIBUTION_METHOD"
        - automatic_code_signing: api-key
        - cache_level: none
    - deploy-to-bitrise-io@2: {}
  run_tests:
    summary: Run your Xcode tests and get the test report.
    description: The workflow will first clone your Git repository, cache and install
      your project's dependencies if any, run your Xcode tests and save the test results.
    steps:
    - git-clone@8: {}
    - restore-spm-cache@1: {}
    - xcode-test@5:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - test_repetition_mode: retry_on_failure
        - cache_level: none
    - save-spm-cache@1: {}
    - deploy-to-bitrise-io@2: {}
  run_tests_2:
    summary: Run your Xcode tests and get the test report.
    description: The workflow will first clone your Git repository, cache and install
      your project's dependencies if any, run your Xcode tests and save the test results.
    steps:
    - git-clone@8: {}
    - restore-spm-cache@1: {}
    - xcode-test@5:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
        - test_repetition_mode: retry_on_failure
        - cache_level: none
        title: Xcode Test for iOS 2
    - save-spm-cache@1: {}
    - deploy-to-bitrise-io@2: {}
  hello_world:
    steps:
    - script@1:
        inputs:
        - content: |
            #!/bin/env bash
            set -ex

            # Creating a sub-directory for the test run within the BITRISE_TEST_RESULT_DIR:

            test_run_dir="$BITRISE_TEST_RESULT_DIR/result_dir_1"
            mkdir "$test_run_dir"

            # Exporting the JUnit XML test report:
            cat << EOF > "$test_run_dir/UnitTest.xml"
            <?xml version="1.0" encoding="UTF-8"?>
            <testsuites>
                <testsuite name="ExampleTestSuite" tests="0" failures="0" errors="0" skipped="0" timestamp="2023-10-05T12:00:00" time="0.123">
                </testsuite>
            </testsuites>
            EOF

            # Creating the test-info.json file with the name of the test run defined:

            echo '{"test-name":"MY TEST RUN NAME"}' >> "$test_run_dir/test-info.json"
    - deploy-to-bitrise-io@2: {}
meta:
  bitrise.io:
    stack: osx-xcode-16.0.x
    machine_type_id: g2-m1.4core
app:
  status_report_name: Executing OPTB <target_id> for <project_title>
  envs:
  - BITRISE_PROJECT_PATH: Addly.xcodeproj
    opts:
      is_expand: false
  - BITRISE_SCHEME: Addly
    opts:
      is_expand: false
  - BITRISE_DISTRIBUTION_METHOD: ad-hoc
    opts:
      is_expand: false
pipelines:
  main-pipeline:
    workflows:
      run_tests: {}
      run_tests_2: {}
      hello_world: {}
    triggers:
      pull_request:
      - target_branch: main
